# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy dotnet core project to Azure Function App - pastia-api
on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x' # Using x to get latest patch version of .NET 8.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3 # Updated to v3 of setup-dotnet
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      # Added step to verify .NET installation
      - name: Verify .NET installation
        run: dotnet --info
      
      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet restore
          dotnet build --configuration Release --output ./output
          popd
      
      # Added step to list output files for debugging
      - name: List output files
        run: |
          find ./output -type f | sort
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'pastia-api'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EEBC439F4F774EE5A665615ABE0C36DE }}
          sku: 'flexconsumption'
      
      # Added step to show deployment result
      - name: Deployment Result
        if: always()
        run: |
          echo "Deployment Status: ${{ steps.fa.outcome }}"
